import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.join(process.cwd(), ".env") });

export default {
  node_env: process.env.NODE_ENV,
  port: process.env.PORT,
  database_url: process.env.DATABASE_URL,
  backend_url: process.env.BACKEND_URL,
  frontend_url: process.env.FRONTEND_URL,
  test_admin_name: process.env.TEST_ADMIN_NAME as string,
  test_admin_email: process.env.TEST_ADMIN_EMAIL as string,
  test_admin_password: process.env.TEST_ADMIN_PASSWORD as string,
  test_courier_name: process.env.TEST_COURIER_NAME as string,
  test_courier_email: process.env.TEST_COURIER_EMAIL as string,
  test_courier_password: process.env.TEST_COURIER_PASSWORD as string,
  bcrypt_salt_rounds: process.env.BCRYPT_SALT_ROUNDS,
  redis_username: process.env.REDIS_USERNAME,
  redis_password: process.env.REDIS_PASSWORD,
  redis_host: process.env.REDIS_HOST,
  redis_port: process.env.REDIS_PORT,
  email_sender: process.env.EMAIL_SENDER,
  smtp_user: process.env.SMTP_USER,
  smtp_password: process.env.SMTP_PASSWORD,
  jwt_access_secret: process.env.JWT_ACCESS_SECRET as string,
  jwt_refresh_secret: process.env.JWT_REFRESH_SECRET as string,
  jwt_access_expires_in: process.env.JWT_ACCESS_EXPIRES_IN!,
  jwt_refresh_expires_in: process.env.JWT_REFRESH_EXPIRES_IN!,
  google_client_id: process.env.GOOGLE_CLIENT_ID,
  cloudinary_cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  cloudinary_api_key: process.env.CLOUDINARY_API_KEY,
  cloudinary_api_secret: process.env.CLOUDINARY_API_SECRET,
  bkash_base_url: process.env.BKASH_BASE_URL,
  bkash_username: process.env.BKASH_USERNAME as string,
  bkash_password: process.env.BKASH_PASSWORD as string,
  bkash_app_key: process.env.BKASH_APP_KEY as string,
  bkash_app_secret: process.env.BKASH_APP_SECRET,
  bkash_callback_url: process.env.BKASH_CALLBACK_URL,
};
